In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics
%matplotlib inline

In [2]:
#read detection dataframe
df=pd.read_csv("Data/train_detection.csv")
df.head()

,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,Homogeneity,...,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized,class
0,4.937605,0.423813,0.894121,0.894121,231.248614,32.252113,0.232233,0.518499,1.458699,0.907496,...,3.548803,12.964904,1.228323,0.423813,0.586963,-0.528501,0.805223,0.976092,0.994058,0
1,2.551722,0.259480,0.871947,0.871947,202.027005,25.453599,0.109989,0.813569,0.644821,0.961702,...,2.583464,7.927913,0.549805,0.259480,0.315387,-0.538252,0.614395,0.989201,0.996550,0
2,6.206039,0.618669,0.881609,0.881609,290.479083,38.493259,0.287417,0.465086,1.622099,0.893214,...,3.951214,16.582751,1.352757,0.618669,0.663400,-0.495262,0.809447,0.971216,0.991679,0
3,1.885596,0.194235,0.828962,0.828962,82.500028,12.126492,0.090015,0.849845,0.524957,0.967822,...,2.379112,5.820273,0.444227,0.194235,0.272537,-0.521013,0.555576,0.991032,0.997319,0
4,4.790395,0.481035,0.890599,0.890599,343.387103,44.837110,0.210380,0.629436,1.159005,0.925256,...,3.366307,14.007415,0.979534,0.481035,0.521808,-0.517051,0.743680,0.979213,0.993550,0

In [4]:
#extract the target feature
y=df['class']
X=df.drop(labels="class",axis=1)
y.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [5]:
X.head()

,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,Homogeneity,...,Sum of sqaures: Variance,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized
0,4.937605,0.423813,0.894121,0.894121,231.248614,32.252113,0.232233,0.518499,1.458699,0.907496,...,5.094305,3.548803,12.964904,1.228323,0.423813,0.586963,-0.528501,0.805223,0.976092,0.994058
1,2.551722,0.259480,0.871947,0.871947,202.027005,25.453599,0.109989,0.813569,0.644821,0.961702,...,2.641339,2.583464,7.927913,0.549805,0.259480,0.315387,-0.538252,0.614395,0.989201,0.996550
2,6.206039,0.618669,0.881609,0.881609,290.479083,38.493259,0.287417,0.465086,1.622099,0.893214,...,6.453880,3.951214,16.582751,1.352757,0.618669,0.663400,-0.495262,0.809447,0.971216,0.991679
3,1.885596,0.194235,0.828962,0.828962,82.500028,12.126492,0.090015,0.849845,0.524957,0.967822,...,1.945784,2.379112,5.820273,0.444227,0.194235,0.272537,-0.521013,0.555576,0.991032,0.997319
4,4.790395,0.481035,0.890599,0.890599,343.387103,44.837110,0.210380,0.629436,1.159005,0.925256,...,4.978558,3.366307,14.007415,0.979534,0.481035,0.521808,-0.517051,0.743680,0.979213,0.993550

In [8]:
#divide data into training and validation data
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2)
X_train.head()

,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,Homogeneity,...,Sum of sqaures: Variance,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized
8,1.755978,0.160803,0.849473,0.849473,119.458388,14.607776,0.061517,0.911256,0.337693,0.980038,...,1.800960,2.282477,5.947551,0.289364,0.160803,0.187016,-0.553897,0.476898,0.994101,0.997899
76,3.083565,0.171906,0.932120,0.932120,240.431281,31.113137,0.099589,0.773229,0.739599,0.959623,...,3.126647,2.759360,9.372006,0.642784,0.171906,0.319255,-0.630030,0.702375,0.989667,0.997547
9,2.109007,0.240043,0.837149,0.837149,127.086262,17.236127,0.100971,0.846573,0.542582,0.965579,...,2.191099,2.443147,6.648933,0.457759,0.240043,0.289083,-0.516572,0.560248,0.990124,0.996776
16,1.549803,0.152416,0.806465,0.806465,83.783393,10.297439,0.056218,0.916714,0.319897,0.981925,...,1.591564,2.220223,5.204663,0.275383,0.152416,0.172770,-0.511659,0.444040,0.994647,0.998036
110,6.917834,0.288524,0.927513,0.927513,94.199686,9.258885,0.234436,0.297486,1.798563,0.891016,...,6.992706,4.504234,16.256027,1.574335,0.288524,0.589873,-0.595180,0.884093,0.974533,0.995658

In [12]:
print(y_train.value_counts())
print(y_val.value_counts())
y_train.head()

1    62
0    34
Name: class, dtype: int64
1    18
0     6
Name: class, dtype: int64

8      0
76     1
9      0
16     0
110    1
Name: class, dtype: int64

In [19]:
#choosing different C values
C=[0.01,0.03,0.1,0.3,1,3,10,30,100]
sigma=[0.01,0.03,0.1,0.3,1,3,10,30,100]

In [20]:
#predict score function
def predict_score(x_test,y_test,x_train,y_train,C,sigma):
    model=SVC(C=C,kernel='rbf',gamma=sigma)
    model.fit(x_train,y_train)
    predictions=model.predict(x_test)
    print(">>>>>>>")
    print("Accuracy: C={} sigma={} is {}".format(C,sigma,metrics.accuracy_score(y_test,predictions)))
    print(">>>>>>>")

<h2>Error Metrics</h2>

In [22]:
#calculate scores
for c_val in C:
    for sigma_val in sigma:
        predict_score(X_val,y_val,X_train,y_train,c_val,sigma_val)

>>>>>>>
Accuracy: C=0.01 sigma=0.01 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.01 sigma=0.03 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.01 sigma=0.1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.01 sigma=0.3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.01 sigma=1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.01 sigma=3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.01 sigma=10 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.01 sigma=30 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.01 sigma=100 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.03 sigma=0.01 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.03 sigma=0.03 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.03 sigma=0.1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.03 sigma=0.3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.03 sigma=1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.03 sigma=3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.03 sigma=10 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.03 sigma=30 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.03 sigma=100 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.1 sigma=0.01 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.1 sigma=0.03 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.1 sigma=0.1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.1 sigma=0.3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.1 sigma=1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.1 sigma=3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.1 sigma=10 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.1 sigma=30 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.1 sigma=100 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.3 sigma=0.01 is 0.7083333333333334
>>>>>>>
>>>>>>>
Accuracy: C=0.3 sigma=0.03 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.3 sigma=0.1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.3 sigma=0.3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.3 sigma=1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.3 sigma=3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.3 sigma=10 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.3 sigma=30 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=0.3 sigma=100 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=1 sigma=0.01 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=1 sigma=0.03 is 0.7083333333333334
>>>>>>>
>>>>>>>
Accuracy: C=1 sigma=0.1 is 0.7083333333333334
>>>>>>>
>>>>>>>
Accuracy: C=1 sigma=0.3 is 0.7916666666666666
>>>>>>>
>>>>>>>
Accuracy: C=1 sigma=1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=1 sigma=3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=1 sigma=10 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=1 sigma=30 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=1 sigma=100 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=3 sigma=0.01 is 0.7083333333333334
>>>>>>>
>>>>>>>
Accuracy: C=3 sigma=0.03 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=3 sigma=0.1 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=3 sigma=0.3 is 0.8333333333333334
>>>>>>>
>>>>>>>
Accuracy: C=3 sigma=1 is 0.7916666666666666
>>>>>>>
>>>>>>>
Accuracy: C=3 sigma=3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=3 sigma=10 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=3 sigma=30 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=3 sigma=100 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=10 sigma=0.01 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=10 sigma=0.03 is 0.875
>>>>>>>
>>>>>>>
Accuracy: C=10 sigma=0.1 is 0.7916666666666666
>>>>>>>
>>>>>>>
Accuracy: C=10 sigma=0.3 is 0.8333333333333334
>>>>>>>
>>>>>>>
Accuracy: C=10 sigma=1 is 0.7916666666666666
>>>>>>>
>>>>>>>
Accuracy: C=10 sigma=3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=10 sigma=10 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=10 sigma=30 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=10 sigma=100 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=30 sigma=0.01 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=30 sigma=0.03 is 0.9166666666666666
>>>>>>>
>>>>>>>
Accuracy: C=30 sigma=0.1 is 0.7916666666666666
>>>>>>>
>>>>>>>
Accuracy: C=30 sigma=0.3 is 0.8333333333333334
>>>>>>>
>>>>>>>
Accuracy: C=30 sigma=1 is 0.7916666666666666
>>>>>>>
>>>>>>>
Accuracy: C=30 sigma=3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=30 sigma=10 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=30 sigma=30 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=30 sigma=100 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=100 sigma=0.01 is 0.7916666666666666
>>>>>>>
>>>>>>>
Accuracy: C=100 sigma=0.03 is 0.9166666666666666
>>>>>>>
>>>>>>>
Accuracy: C=100 sigma=0.1 is 0.7916666666666666
>>>>>>>
>>>>>>>
Accuracy: C=100 sigma=0.3 is 0.8333333333333334
>>>>>>>
>>>>>>>
Accuracy: C=100 sigma=1 is 0.7916666666666666
>>>>>>>
>>>>>>>
Accuracy: C=100 sigma=3 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=100 sigma=10 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=100 sigma=30 is 0.75
>>>>>>>
>>>>>>>
Accuracy: C=100 sigma=100 is 0.75
>>>>>>>

In [ ]:
#so, at C=30 and sigma =1 and C=100 and sigma=0.03 , we get 91.66 percent accuracy for rbf kernel